# Generated by Django 3.0.7 on 2020-11-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('rif', models.CharField(blank=True, max_length=8, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telf', models.IntegerField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
