# Generated by Django 3.0.7 on 2020-11-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='tienda',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telf',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
