# Generated by Django 3.0.7 on 2020-11-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201119_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('presio', models.CharField(max_length=15)),
                ('descripcion', models.TextField()),
                ('img_producto', models.ImageField(upload_to='')),
                ('delivery', models.CharField(choices=[('yes', 'si'), ('not', 'no')], default='yes', max_length=3)),
                ('pick_up', models.CharField(choices=[('yes', 'si'), ('not', 'no')], default='yes', max_length=3)),
            ],
        ),
    ]
