# Generated by Django 3.0.7 on 2020-11-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201124_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='img_producto',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='perfil'),
        ),
    ]
