# Generated by Django 3.0.7 on 2020-11-24 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201124_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
