# Generated by Django 3.0.7 on 2020-12-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_tienda_banner_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='delivery',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='si', max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='pick_up',
            field=models.CharField(choices=[('si', 'si'), ('no', 'no')], default='si', max_length=3),
        ),
    ]
